version: "3.8"

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.9.0
    restart: always
    environment:
      - ELASTIC_USERNAME=maktaba
      - ELASTIC_PASSWORD=maktaba@2022!
      - xpack.security.enabled=true
      - discovery.type=single-node
      - ingest.geoip.downloader.enabled=false
      - xpack.security.transport.ssl.enabled=true
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    volumes:
      - elastic:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: kibana:8.9.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=maktaba
      - ELASTICSEARCH_PASSWORD=maktaba@2022!
      - xpack.security.enabled=true
      - xpack.reporting.roles.enabled=false
    networks:
      - elastic
    volumes:
      - elastic:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

volumes:
  elastic:
    external: true

networks:
  elastic:
    external: true
